[[configs]]
tp = 2
dp = 1
pp = 1
model = "llama_3_8b"
sequence_length = 4096
micro_batch_size = 1  # OOM with larger batch size

# tp=2, dp=2, pp=1, mbz=1 fails :/

[[configs]]
tp = 4
dp = 1
pp = 1
model = "llama_3_8b"
sequence_length = 4096
micro_batch_size = 4  # OOM with larger maybe?

[[configs]]
tp = 2
dp = 4
pp = 1
model = "llama_3_8b"
sequence_length = 4096
micro_batch_size = 2

[[configs]]
tp = 4
dp = 1
pp = 2
model = "llama_3_8b"
sequence_length = 4096
micro_batch_size = 2

[[configs]]
tp = 4
dp = 2
pp = 1
model = "llama_3_8b"
sequence_length = 4096
micro_batch_size = 2
