general:
  project: benchmark-v0.1
  seed: 42
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.025
  make_vocab_size_divisible_by: 1
  model_config:
    hidden_act: silu
    initializer_range: 0.02
    is_llama_config: true
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    tie_word_embeddings: false
    use_cache: true
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0001
    lr_decay_style: linear
    lr_warmup_style: linear
    lr_warmup_steps: 1
    min_decay_lr: 1.0e-05
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.01
  zero_stage: 1
parallelism:
  expert_parallel_size: 1
  tp_linear_async_communication: false
  tp_mode: REDUCE_SCATTER
data_stages:
  - name: Stable Training Stage
    start_training_step: 1
    data:
      dataset:
        dataset_overwrite_cache: false
        dataset_processing_num_proc_per_process: 64
        hf_dataset_config_name: null
        hf_dataset_or_datasets: DKYoon/SlimPajama-6B
        hf_dataset_splits: train
        text_column_name: text
      num_loading_workers: 32
      seed: 42
lighteval: null
tokens:
  train_steps: 20
  val_check_interval: -1
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
checkpoints:
  checkpoint_interval: 100000
  checkpoints_path: /dev/null
  resume_checkpoint_path: null
