image = "/bret/scratch/cscs/ahernnde/container-image/llm/llm-v1.0.sqsh"
mounts = [
	"/bret:/bret",
	"/etc/slurm:/etc/slurm",
	"/users/ahernnde:/users/ahernnde",
	"/usr/lib64/libnl-3.so:/usr/lib/libnl-3.so",
	"/usr/lib64/libnl-3.so.200:/usr/lib/libnl-3.so.200",
	"/usr/lib64/libnl-3.so.200.25.0:/usr/lib/libnl-3.so.200.25.0",
	"/bret/scratch/cscs/manitart/aws-ofi-nccl/1.6.0-hcopy/libnccl-net.so:/usr/lib/libnccl-net-ofi.so",
]
writable = true

[env]
ENROOT_CXI_HOOK = "1"
NCCL_NET_PLUGIN = "ofi"
